### ISSUE TITLE
Why you use " _merge([z ,y, t]) " ?

### ISSUE THREAD

**Issue by AricJames** [TheShadow29/VC-with-GAN#2]
Dear friend:
Why you use " _merge([z ,y, t]) " and " _merge([z, y, i_vec]) " in the generator instead of using " concat(z, y, t) "? I do not understand the meaning of "+" in "x = x + slim.fully_connected(var)"?  
I'm sorry to bother you. Could you tell me why? Thank you very much.

**Comment by TheShadow29** [comment]
Hi @shiyangccy. Sorry for the delayed reply. Unfortunately, I don't have a solid answer for you. We borrowed that part of the code from https://github.com/JeremyCCHsu/vae-npvc (who is the original author of voice conversion with gan though the linked repository is using variational autoencoder). So it might be a better idea to ask in the linked repository.
